#!/usr/bin/env bash
# @Author: Thomas Foubert <tfoubert>
# @Date:   2019-04-25T17:50:59+02:00
# @Email:  thomas@thomas-foubert.com
# @Filename: autotunnel
# @Last modified by:   thomas
# @Last modified time: 2019-05-13T18:03:32+02:00

helper () {
    echo "USAGE: ${0} [-h/--help] alias-name local-port remote-port"
    echo "DESCRIPTION: "
    echo -e "\t-h/--help\t\tDisplay this helper"
    echo -e "\talias-name\t\tThe alias you want to give to your tunnel"
    echo -e "\tlocal-port\t\tThe targeted local port for your tunnel"
    echo -e "\tremote-port\t\tThe targeted remote port for your tunnel\n"
    echo "The script must be run under root or sudo permisions"
    exit $1
}

if [[ "$1" = "-h" ]] || [[ "$1" = "--help" ]]; then
    helper 0
fi

if ! [ $(id -u) = 0 ]; then
   echo "The script must be run under root or sudo permisions." >&2
   exit 1
fi

if [[ -z $1 ]] || [[ -z $2 ]] || [[ -z $3 ]]; then
    echo "Missing argument." >&2
    helper 1
elif [[ -n $4 ]]; then
    echo "Too much arguments." >&2
    helper 1
fi

if [ -z /usr/bin/autossh ]; then
    echo "Installing autossh"
    apt install autossh
fi

cp basefile.txt autossh-tunnel.service
sed -i.bak s/alias/${1}/g autossh-tunnel.service
sed -i.bak s/lport/${2}/g autossh-tunnel.service
sed -i.bak s/rport/${3}/g autossh-tunnel.service
rm *.bak
mv autossh-tunnel.service /etc/systemd/system/
mkdir -p ~/.ssh
touch ~/.ssh/known_hosts
ssh-keyscan -H serveo.net >> ~/.ssh/known_hosts
systemd daemon-reload
systemd enable autossh-tunnel.service
systemd start autossh-tunnel.service
